### ISSUE TITLE
Preferred name for credit in Racket release notes?

### ISSUE THREAD

**Issue by jbclements** [KDr2/kdr2-on-web#1]
I'm John Clements, the release manager for Racket, and I'm wondering how you'd like to be credited in the Racket v7.7 release announcement. Your web page suggests that "ZHUO Qingliang" is the right string to use. Let me know if I'm mistaken!

**Comment by KDr2** [comment]
> Your web page suggests that "ZHUO Qingliang" is the right string to use. 

Yeah, that’s it :)
